### ISSUE TITLE
Making a better, safer, DVWA pull request

### ISSUE THREAD

**Issue by Shinkurt** [RandomStorm/DVWA#23]
Hey,

I have talked with @ethicalhack3r and made changes to DVWA. fixing major unintended holes and some others that explained in http://www.paulosyibelo.com/2014/09/dvwa-unintended-security-issues.html

Other than that, fixed the Rosetta Flash attack for the high level, added some extra protection layers as a "high" level, and modified the graphics a lot.

I personally don't know how to use github to pull a request (*embarrassed*); neither do I have time. contacted ryan and he told me the same thing so, we were hoping some from here can do that for me and pull the newest, cooler, DVWA.

Here: can you try https://www.dropbox.com/s/s0t8rjm4vhlkllu/dvwa-final.zip?dl=0

Thanks,

**Comment by Kentsson** [comment]
Looks good, will try it out this weekend.

**Comment by ethicalhack3r** [comment]
Hey! Apologies for the unacceptable delay on this one but there are some reasons why the delay has been caused.

I personally no longer actively maintain this project but I am happy to do the minimum to keep the project alive. Such as keeping the dvwa.co.uk website up and providing some support.

Because I no longer actively maintain the project I don't have the will to put in any significant amount of my time to implement new features / fix bugs.

Reviewing a .zip file of the code requires much more time than if you had created a pull request as I had requested via email. But even then, I'm sorry to say that it wouldn't have been a priority of mine. Although, others may have had the opportunity to review the changes and implement them.

Personally, I don't like the UI changes (the Matrix styling) but I do think your bug fixes would be useful.

I would still recommend creating a pull request and hopefully someone will review the changes in the future if you are still willing to do so.

Alternatively as it is open source you could fork the project and maintain your own version.

**Comment by g0tmi1k** [comment]
This seems to be based on the v1.0.7 ZIP file from: http://sourceforge.net/projects/dvwa/files/DVWA-1.0.7.zip/download
Note, this is not exactly the same as SVN revision 70 (https://svn.code.sf.net/p/dvwa/code/) - which only makes understanding what's what more of a pain...

From what I can tell, @Shinkurt changes are:
+ New theme 
  - Personally I like the layout more, and styling. However I don't like the background or the dark design - doesn't look as professional & harder on the eyes.
+ `<form` in `./vulnerabilities/*/index.php` have been altered to be above the `<div` tags
  -  Not sure why, as HTML ordering is out of sync now.
+ `generateTokens()` on `./vulnerabilities/exec/index.php` - as well as `checkTokens($_POST['token'] , "./");` on all `/vulnerabilities/exec/source/*`.
+ `./vulnerabilities/upload/index.php` has `enctype="multipart/form-data"` set in the form tag.
+ `./vulnerabilities/upload/{low|medium}.php` sets filenames to MD5 sums.
  - Not sure if I agree with this on the low level.
+  `./vulnerabilities/upload/high.php` - additional headers as well as other type check (as in medium level) and `getimagesize()`.
+ `./vulnerabilities/view_help.php` - `xss_filter()` used on `$_GET[ 'id' ]` & additional headers.
  - There's also what looks like 'left over' debug statements 
  - as well as a ` $_GET[ 'security' ]` (without the `xss_filter()`) & `challenges` that are not used?
+ `./vulnerabilities/view_source_all.php` - `xss_filter()` used on `$_GET[ 'id' ]` & additional headers.
+ `./vulnerabilities/view_source.php` - `xss_filter()` used on `$_GET[ 'id' ]`,` $_GET[ 'security' ]` & additional headers.
  - `$security` looks like it is being defined twice.
+ `./setup.php` - `generateTokens()` & `checkTokens($_POST['token'] , "./");` in 
+ `./security.php` - `generateTokens()` & `checkTokens($_POST['token'] , "./");`
+ `new.php` - new file.
  - Looks like 'left over' debug statements
+ `./login.php` - additional headers 
+ `./hackable/uploads/*` - 5 new files
  - Looks like 'left over' backdoor files.
+ `./external/phpids/0.6/*` - various files (*.html?) have been removed from `docs` and `test`
+ `./dvwa/includes/dvwaPage.inc.php` - `xss_filter()` on `dvwaPageReload()`, 4x new token functions, another redirect method (duplicated) & additional headers.
+ `/dvwa/includes/dvwaHeaders.php` - various hardening headers

**Comment by Shinkurt** [comment]
@g0tmi1k yes. that's pretty much it. my code rewrites, most of which are actually meant to fix some bugs. and the <div and <form attribution is simply a styling thing. also some of the files are actually a mistakely left-over files you are right. the .htaccess files are deleted in mistake

Anyway, the fact they are other branches makes sense that Github coudn't make a compare and I couldn't make a pull request. so I will be glad if someone did so.

Thanks,

**Comment by g0tmi1k** [comment]
@Shinkurt 
The naming of the software indicates there's various vulnerability with the software. Plus the documentation does state there are documented and undocumented vulnerability with it (as well as not to use it anywhere exposed to the Internet).
Using your suggested fixes, you will remove various of the undocumented issues with it (such as the LFI in view_source*.php). I personally think they are a great little easter egg in the software - and that it should encourage students to poke about/finds issues/easter eggs.
Saying that, I do think some type of CSRF on `setup.php` should be included. Adding it to `login.php` might be a good idea _(will add another challenge for people wanting to brute force it )_ - as these are pre-auth. However I believe the other issues are all post-auth (XSS/LFIs) and they should stay.
Adding all those headers might make it too secure (e.g. stops phishing with XSS).

You cannot merge your work into it directly because your project doesn't share the same git history as RandomStorm's project (not sure how you forked it).
Either way, your work is all based on SVN revision 70 (DVWA v1.0.7), which is dated as it's now on GIT (DVWA v1.8). As there's no source code control on your fork, it's very hard to know what work you have done to it (e.g. there's no history). This means its a lot of manual work to figure out your changes, let alone adding it to the current version. 

If you want help learning git, you can find me on IRC and I would be more than happy to help out.

**Comment by digininja** [comment]
I agree, leave the undocumented features in there, they give it more
character and make it more fun to give to students.

**Comment by Shinkurt** [comment]
@g0tmi1k @digininja agreed! I think the CSRF that cause the RCE should be fixed. I didn't notice the documentation on those issues could be eastereggs.

However, I still think all the bug fixes in the "High" level should still be committed. I am talking about the once that cause XSCH, the content-sniffing XSS and stuff. I am saying that because the **High** level is meant to be actually secure. some people, the students actually learn from the code on what is secure and is meant to be unbroken.

That as it may, I agree the eastereggs should remain as is. I'll also be happy if you can add me in the about.php page. dont put a giveaway comments and ofcourse, help launch it. I am currently on a mobile so its very unlikely I will be able to use git anytime soon.

Thanks,
P

**Comment by g0tmi1k** [comment]
CSRF added with #43! =)
I didn't add the File Upload protection you did for 'high' as I have got something large plan for that....

**Comment by ethicalhack3r** [comment]
OK to close the issue?

**Comment by Shinkurt** [comment]
@ethicalhack3r @digininja @g0tmi1k credit at about.php would be nice. :+1:
